version: '3.8'

services:
  authentication:
    image: authentication-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "pnpm prisma migrate deploy && pnpm start"
    dns:
      - 8.8.8.8  # Google DNS server
      - 8.8.4.4  # Google DNS server

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
