// src/core/exception/error-codes.ts
// Centralized error code catalog for the Flipxer API

/**
 * Error codes for structured API error responses.
 * These codes allow the frontend to reliably identify error types
 * without fragile regex pattern matching on error messages.
 */
export enum ErrorCode {
    // === AUTHENTICATION ===
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED",
    ACCOUNT_DISABLED = "ACCOUNT_DISABLED",
    ACCOUNT_FLAGGED = "ACCOUNT_FLAGGED",
    SESSION_EXPIRED = "SESSION_EXPIRED",
    INVALID_TOKEN = "INVALID_TOKEN",
    UNAUTHORIZED = "UNAUTHORIZED",

    // === TWO-FACTOR AUTHENTICATION ===
    TWO_FACTOR_REQUIRED = "TWO_FACTOR_REQUIRED",
    INVALID_2FA_CODE = "INVALID_2FA_CODE",
    TWO_FACTOR_LOCKED = "TWO_FACTOR_LOCKED",
    INVALID_BACKUP_CODE = "INVALID_BACKUP_CODE",
    TWO_FACTOR_NOT_ENABLED = "TWO_FACTOR_NOT_ENABLED",

    // === EMAIL / OTP VERIFICATION ===
    INVALID_OTP = "INVALID_OTP",
    OTP_EXPIRED = "OTP_EXPIRED",
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
    PHONE_NOT_VERIFIED = "PHONE_NOT_VERIFIED",

    // === IDENTITY VERIFICATION (KYC) ===
    BVN_VERIFICATION_FAILED = "BVN_VERIFICATION_FAILED",
    NIN_VERIFICATION_FAILED = "NIN_VERIFICATION_FAILED",
    DOCUMENT_VERIFICATION_FAILED = "DOCUMENT_VERIFICATION_FAILED",
    VERIFICATION_REQUIRED = "VERIFICATION_REQUIRED",
    DUPLICATE_VERIFICATION = "DUPLICATE_VERIFICATION",
    DETAILS_MISMATCH = "DETAILS_MISMATCH",

    // === BANK ACCOUNTS ===
    INVALID_ACCOUNT_NUMBER = "INVALID_ACCOUNT_NUMBER",
    BANK_NOT_FOUND = "BANK_NOT_FOUND",
    ACCOUNT_VERIFICATION_FAILED = "ACCOUNT_VERIFICATION_FAILED",
    ACCOUNT_NAME_MISMATCH = "ACCOUNT_NAME_MISMATCH",
    BANK_ACCOUNT_EXISTS = "BANK_ACCOUNT_EXISTS",

    // === TRANSACTIONS ===
    INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE",
    DAILY_LIMIT_EXCEEDED = "DAILY_LIMIT_EXCEEDED",
    MINIMUM_AMOUNT = "MINIMUM_AMOUNT",
    MAXIMUM_AMOUNT = "MAXIMUM_AMOUNT",
    TRANSACTION_FAILED = "TRANSACTION_FAILED",
    QUOTE_EXPIRED = "QUOTE_EXPIRED",
    INVALID_WALLET_ADDRESS = "INVALID_WALLET_ADDRESS",
    DUPLICATE_TRANSACTION = "DUPLICATE_TRANSACTION",

    // === VALIDATION ===
    VALIDATION_ERROR = "VALIDATION_ERROR",
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD",
    INVALID_INPUT = "INVALID_INPUT",

    // === RATE LIMITING ===
    RATE_LIMITED = "RATE_LIMITED",
    TOO_MANY_ATTEMPTS = "TOO_MANY_ATTEMPTS",

    // === RESOURCES ===
    NOT_FOUND = "NOT_FOUND",
    CONFLICT = "CONFLICT",
    FORBIDDEN = "FORBIDDEN",

    // === SYSTEM ===
    SERVER_ERROR = "SERVER_ERROR",
    DATABASE_ERROR = "DATABASE_ERROR",
    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR",
    UNKNOWN_ERROR = "UNKNOWN_ERROR",
}

/**
 * Helper to create a structured error response
 */
export interface StructuredError {
    message: string;
    code: ErrorCode;
    details?: Record<string, unknown>;
}

export function createError(
    code: ErrorCode,
    message: string,
    details?: Record<string, unknown>
): StructuredError {
    return { code, message, details };
}
